### ISSUE TITLE
dropdown not working

### ISSUE THREAD

**Issue by ac0415** [seyhunak/twitter-bootstrap-rails#243]
Hi,

I'm working on a project and I'm trying to get the dropdown menu to work. It was working bfore my friend merged it with his branch and somehow it just stopped working. can anybody help me?

thanks

http://jsfiddle.net/ac0415/FLVfZ/1/

**Comment by talha9123** [comment]
Hi,
I have an issue with bootstrap dropdown menu...it opens on the first click but when I again click on it it doesn't open.And one more thing that the navigation between two dropdowns also not working...
Please help me!

**Comment by NaveenAmbulapodi** [comment]
Hi, Drop down menu is not working, please help me to solve the problem
