### ISSUE TITLE
translation missing: en.breadcrumbs.controller.index

### ISSUE THREAD

**Issue by prodigerati** [seyhunak/twitter-bootstrap-rails#483]
I just upgraded today and ran the :install command now the breadcrumb helper seems to be broken. Instead of the first crumb being index I am getting an error:

```
translation missing: en.breadcrumbs.tickets.index
```

twitter-bootstrap-rails (2.1.9)
rails (3.2.9)

I have this at the top of my controller per the readme:

```
add_breadcrumb :index, :tickets_path
```

Here is my show action: (displays correctly)

```
def show
    add_breadcrumb @ticket.title, ticket_path(@ticket)
    respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @ticket }
    end
end
```

breadcrumb looks like this:

```
translation missing: en.breadcrumbs.tickets.index / The first Issue Ticket!
```

It was working correctly before I made the upgrade.

**Comment by bistanil98** [comment]
Facing Save issue @prodigerati
