### ISSUE TITLE
Static file missing

### ISSUE THREAD

**Issue by bobzsj87** [seyhunak/twitter-bootstrap-rails#534]
After running all the commands instructed, like rails g bootstrap:install static, the static files still missing. I have updated the gem to point to the lasted github repo.

Any ideas how to solve this?

Error log below:
Showing /home/bobzhou/www/sandbox/testapp/app/views/layouts/application.html.erb where line #15 raised:

cannot load such file -- less
  (in /home/bobzhou/www/sandbox/testapp/app/assets/stylesheets/bootstrap_and_overrides.css.less)
Extracted source (around line #15):

12:       <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
13:     <![endif]-->
14: 
15:     <%= stylesheet_link_tag "application", :media => "all" %>
16: 
17:     
18:     
Rails.root: /home/bobzhou/www/sandbox/testapp

**Comment by mansipathak** [comment]
Hi @bobzsj87 
I am running into the same error you mentioned above. Can you let me know what solution eventually worked for you?
Thanks!
