### ISSUE TITLE
LoadError , The specified module could not be found, Uninitialized constant V8:JSON

### ISSUE THREAD

**Issue by ghost** [seyhunak/twitter-bootstrap-rails#744]
Hey,

I am running on Rails 4 , Ruby 2.0.0p195. Windows 7 x64bit

in my gem file 

```
gem "less-rails"

gem "libv8", "3.16.14.3"`

gem "therubyracer", :require => 'v8'

 gem "twitter-bootstrap-rails"
```

First, I encountered problems installing libv8, but I managed to solve it by downloading the gem  'manually' and `cd` to its directory, and install with --options .

Once I was able to install it and configure my app to use everything needed, I ran the `rails server` and I got this

LoadError Message  Pointing at that line with stars

```


<meta name="viewport" content="initial-scale=1.0, user-scalable=no">
            <meta charset="utf-8">
The specified module could not be found.- C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/therubyracer-0.11.0beta1-x86mingw32/lib/v8/init.so
  (in C:/Sites/testp/project-javascript/app/assets/stylesheets/bootstrap_and_overrides.css.less)

        **  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %> **
          <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
          <%= csrf_meta_tags %>
```

And I refreshed the page and and got this 

```
uninitialized constant V8::JSError
```

Dunno why it gives two different error messages without me rebooting the server nor changing a thing.

I already checked : https://github.com/seyhunak/twitter-bootstrap-rails/issues/206

Help.

**Comment by joshco** [comment]
@psycatham how did you solve this for windows?  I'm trying to get the rubyracer for windows gem to work but am getting that same error - could not find module init.so.
Any words of wisdom?

**Comment by HOuaghad** [comment]
I apologize @joshco, I do not remember much about this since it was 2 years ago.
