### ISSUE TITLE
glyph not working on Ruby 2.2.0, Rails 4.1

### ISSUE THREAD

**Issue by xangelux** [seyhunak/twitter-bootstrap-rails#826]
I try to use the method glyph like it shows on the documentation but that yields the error:

no implicit conversion of Symbol into Integer

The code I use is a copy/paste of glyph(:pencil)

**Comment by vyorkin** [comment]
:+1:
it is fixed in master brunch though

**Comment by toadkicker** [comment]
I forked this project and continued releases. Check out https://github.com/toadkicker/railsstrap.
