### ISSUE TITLE
customize views by `rails g bootstrap:themed`

### ISSUE THREAD

**Issue by gabrieltong** [seyhunak/twitter-bootstrap-rails#828]
hey there , this command is very useful , I always use it when I create new views 

but I need to make changes , and the changes are always the same , can I change the scaffolds my self ?

**Comment by toadkicker** [comment]
Generators are meant to get you going with a basic understanding of your model. It isn't meant to be an end solution to designing things; that's where the components bootstrap and others come in. You can customize bootstrap by overriding the values in bootstrap's variables.less file with the install generator's  bootstrap_overrides.less file. You can also configure rails to use a [specific template for scaffolding your app as well](http://daniel.fone.net.nz/blog/2014/02/01/customising-scaffold-views-in-ruby-on-rails/).

**Comment by gabrieltong** [comment]
@toadkicker thanks man!
