### ISSUE TITLE
Security fixes? 

### ISSUE THREAD

**Issue by mawiegand** [seyhunak/twitter-bootstrap-rails#831]
Will this gem get any security fixes or does the development of this project stop completely? 
We are using this gem for our new website [BluePanel/rails-website](https://github.com/BluePanel/rails-website). So would it be wise to switch to [toadkicker/railsstrap](https://github.com/toadkicker/railsstrap)?

**Comment by toadkicker** [comment]
Yes switch. There hasn't been a gem release from here in over a year.

**Comment by seyhunak** [comment]
I'll bump updates today, specially version changes, bootstrap and fontawesome updates etc. to Rubygems, so officially supporting continues.
