### ISSUE TITLE
Version 3.2.1 of gem will not install with Rails 4 

### ISSUE THREAD

**Issue by turnerking** [seyhunak/twitter-bootstrap-rails#832]
With this commit 704ff4cc3a64c3579e2bafc412fa83da637fb122 and switching all the dependencies to be `~>3.1` instead `>=3.1`, this effectively dropped support for Rails 4 from this version.

```
Fetching gem metadata from https://rubygems.org/........
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    twitter-bootstrap-rails (= 3.2.1) ruby depends on
      railties (~> 3.1) ruby

    meta_request (= 0.2.8) ruby depends on
      railties (4.1.1)
```

**Comment by seyhunak** [comment]
@turnerking fixed typo in master. thanks.

**Comment by toadkicker** [comment]
@seyhunak Considerer yanking 3.2.1 from rubygems please. People would be downloading a broken version now.
