### ISSUE TITLE
Upgrade integrated font-awesome to 4.3.0

### ISSUE THREAD

**Issue by skladd** [seyhunak/twitter-bootstrap-rails#835]
Font awesome v4.3.0 with 40 new icons is available since 22 Jan 2014. It would be awesome :smile: to have them integrated.
https://github.com/FortAwesome/Font-Awesome/releases/tag/v4.3.0

**Comment by toadkicker** [comment]
You can use the CDN version by changing the URL in bootstrap overrides until a new release of this gem comes out that fixes it. Or use my fork, [railsstrap](https://github.com/toadkicker/railsstrap), which supports swapping between versions very easy to do.

**Comment by skladd** [comment]
Hi Todd,
I fixed it meanwhile by serving the font files directly from my app.
Thanks for the hint, I will take a look at your fork.
Stephan

**Comment by panmari** [comment]
Recently, fontawesome v4.4.0 was merged into master, so I think this can be closed.
