### ISSUE TITLE
Getting undefined method `[]' for nil:NilClass after installation

### ISSUE THREAD

**Issue by ahmad19** [seyhunak/twitter-bootstrap-rails#862]
I followed the as usual installation process, but i got this error. 

Below is the screen shot: 
 
![screen shot 2015-06-21 at 5 38 06 pm](https://cloud.githubusercontent.com/assets/2041827/8271574/95fde956-183c-11e5-9743-40e04c3e6289.png)

**Comment by irohiroki** [comment]
update less-rails to 2.7.0. https://github.com/metaskills/less-rails/issues/100

**Comment by ahmad19** [comment]
It worked!  Thanks

**Comment by hunterae** [comment]
Worked for me as well. Thanks!
