### ISSUE TITLE
Rails 5 NoMethodError for "register_preprocessor"

### ISSUE THREAD

**Issue by ccallebs** [seyhunak/twitter-bootstrap-rails#863]
When working with the current Rails 5 alpha, I found an issue when trying to run `rails generate bootstrap:install less`. It's a bug in the less-rails gem documented at metaskills/less-rails#106. It may be too early to think about a Rails 5 branch, but this issue will need to be resolved once it's created.

**Comment by jalexy12** [comment]
you have to revert to the old version of sprockets

**Comment by xujianmin** [comment]
Try sprockets 3.4.0 and sprockets-rails 2.3.3

Can revise them in the Gemfile.lock
