### ISSUE TITLE
Mobile navbar does not collapse after first expand

### ISSUE THREAD

**Issue by maxmnts** [seyhunak/twitter-bootstrap-rails#869]
The navbar on mobile device does not collapse after expanding the menu once.

Using Ruby 2.0.0-p645, the Gemfile I'm using is:

```ruby
source 'https://rubygems.org'

gem 'rails', '3.2.21'

gem 'sqlite3'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'

  gem 'twitter-bootstrap-rails', :git => 'git://github.com/seyhunak/twitter-bootstrap-rails.git'
  gem "less-rails" #Sprockets (what Rails 3.1 uses for its asset pipeline) supports LESS
end

gem 'jquery-rails'
```

The example I used to generate the navbar is taken from [http://bootstrapdocs.com/v3.2.0/docs/components/#navbar-default]

As for a stacktrace, I was unable to capture/replicate a log through my browser. However, I did catch a glimpse of a deprecation warning of what I think originated from jQuery.

**Comment by palidanx** [comment]
After browsing around, I saw doing this works

http://stackoverflow.com/questions/25878450/bootstrap-collapsed-navbar-buggy-open

```
.navbar-collapse.collapse.in {
  display: block!important;
}
```

**Comment by maxmnts** [comment]
Thanks @palidanx !

**Comment by palidanx** [comment]
But shouldn't this work though?  I kind of feel that the css is a patch.  I tested it with an earlier version of bootstrap 3 and it worked so something is funky.
