### ISSUE TITLE
Drop font-awesome support

### ISSUE THREAD

**Issue by fabn** [seyhunak/twitter-bootstrap-rails#889]
I think that font-awesome support does not belong to this gem. In my opinion you should remove it.

For rails pipeline there's the awesome [font-awesome-rails gem](https://github.com/bokmann/font-awesome-rails) which also provides helpers to generate icons in views.

If you want I can sketch a PR that remove FA support and point users to that gem to have it in their projects. If you're interested I'd still keep glyphicons out of default generated less file because I think that FA is a far superior solution for font icons.

What do you think?

**Comment by seyhunak** [comment]
@fabn That would be great! F.A maintaince requires extra effort. You can drop me PR's so we can review it. I'll happily support process. Thanks.

**Comment by fabn** [comment]
@seyhunak I created a PR for this. Let me know.

P.S. may I ask you to add tags to this repository. It's a little bit hard to upgrade a such widely used gem without seeing what's changed from one version to another.

Thanks.
