### ISSUE TITLE
Bug error_span in templete

### ISSUE THREAD

**Issue by qx** [seyhunak/twitter-bootstrap-rails#903]
error_span in templete. [ http://stackoverflow.com/questions/26245222/undefined-method-error-span-rails-project/36120983#36120983l](http://stackoverflow.com/questions/26245222/undefined-method-error-span-rails-project/36120983#36120983)

**Comment by Stormcore** [comment]
Also have this issue

**Comment by qx** [comment]
@Stormcore  I suggest u to use bower without bs3 rails.

**Comment by Stormcore** [comment]
@qx bad suggestion, bower will not provide some awesome helpers this gem provides out of the box

**Comment by qx** [comment]
@Stormcore  I don't think so.
