### ISSUE TITLE
Problem with DEPRECATED warnings for Rails 4

### ISSUE THREAD

**Issue by abitrolly** [seyhunak/twitter-bootstrap-rails#939]
**Describe the bug**

The warning below is issued every time a Rail 4 project is built.
```
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
       Please register a mime type using `register_mime_type` then
       use `register_compressor` or `register_transformer`.
```
The error for Rails 5 is fixed by https://github.com/seyhunak/twitter-bootstrap-rails/commit/553e785cbfbfba99443b63ae1fcd8882d2c8eef1 which is in `master`, but not released.

Is would be very nice if a backport of 3.x version of `twitter-bootstrap-rails` could be released with this bugfix. Because 4.x is not compatible with Rails 4.

https://github.com/seyhunak/twitter-bootstrap-rails/blob/a9a5b41735cdb37e0dcb878eb25dcdf6174412cd/twitter-bootstrap-rails.gemspec#L22

**Comment by abitrolly** [comment]
Fixed by upgrading `less-rails` from `~> 2.7.0` to `~> 4.0.0`.

**Comment by seyhunak** [comment]
Can you make a PR @abitrolly if it is possible?

**Comment by abitrolly** [comment]
@seyhunak done above.
